### ISSUE TITLE
Error Massage in LOG

### ISSUE THREAD

**Issue by verne2021** [Micha95/homeassistant_timetree_calendar#2]
Hi together,
Hi Micha,

I get this error massage in server log and the calendar is not available.

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform await asyncio.shield(task) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/timetree/calendar.py", line 34, in setup_platform calendars = timetree_object.get_calendars() AttributeError: 'str' object has no attribute 'get_calendars'

For additional information, I have more calendars on timetree configuration. Is there any point what I must consider?

**Comment by Wxam** [comment]
Hey,

Did you do this step aswell?

Create your Token here: https://timetreeapp.com/developers/personal_access_tokens
After that, replace the 'YOURAPIKEY' in Calendar.py with your Token

**Comment by verne2021** [comment]
Hi, yes i do this step more as one time.
But i can't See any changes at the timetree dev. It shows me all the time "unused" 

I have 5 different calenders in my timetree Account. Is this an issue?

**Comment by Wxam** [comment]
> Hi, yes i do this step more as one time. But i can't See any changes at the timetree dev. It shows me all the time "unused"
> 
> I have 5 different calenders in my timetree Account. Is this an issue?

As far as I know this won't be a problem, I had 2 and they showed up without a problem.
Are you also sure every single file is right? because I had to do some changes within some .py files before it worked

**Comment by verne2021** [comment]
Which changes in Which files do you have made?
I have checked the changes in issue 1 with no success.

**Comment by Wxam** [comment]
You gotta check all the files for the __init__ I had one file that at some point just had init without the __ in front and back of it
