### ISSUE TITLE
Calendar not pulling data

### ISSUE THREAD

**Issue by Wxam** [Micha95/homeassistant_timetree_calendar#3]
I've a issue that My calendar is not pulling in any data from the actual TimeTree Calendar.
It did add all the calendars I have but in Home-Assistant the calendar is empty even tho there are a lot of events in the actual calendar.

I don't get any error logs so I can't find the actual issue.
Personal Token is also getting used and has all the rights.
![image](https://user-images.githubusercontent.com/20145041/158387379-210f19eb-8c66-489c-9744-68ef302d6e29.png)

Hope you can help me out on this one

**Comment by Wxam** [comment]
Just found out that it does put some info into the log.

> Logger: homeassistant.helpers.entity
Source: custom_components/timetree/calendar.py:148
Integration: timetree ([documentation](https://home.koster-itsupport.nl/config/none), [issues](https://home.koster-itsupport.nl/config/none))
First occurred: 2:13:30 PM (138 occurrences)
Last logged: 3:21:31 PM

Update for calendar.family fails
Update for calendar.family_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timetree/calendar.py", line 74, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/timetree/calendar.py", line 148, in update
    start = entity.attributes.start_at
AttributeError: 'EventAttributes' object has no attribute 'start_at'

Hope this helps with finding the solution

**Comment by Wxam** [comment]
Fixed this issue, I found out that one of the .py was missing __init__ as it just said init
Seems to work fine now
