### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'location_lat'

### ISSUE THREAD

**Issue by thstorm** [Micha95/homeassistant_timetree_calendar#4]
Hi,

i am trying to use your time tree intergation.

I have done a git clone in my custom_componet directory, changed my api_key and activated in in my configuration.yaml.

But I alway get this Error 

Logger: homeassistant.components.calendar
Source: custom_components/timetree/timetree_sdk/models/base.py:11 
Integration: Kalender ([documentation](https://www.home-assistant.io/integrations/calendar), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+calendar%22)) 
First occurred: 18:21:13 (1 occurrences) 
Last logged: 18:21:13

Error while setting up timetree platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timetree/calendar.py", line 38, in setup_platform
    EntitiesCalendarDevice(
  File "/config/custom_components/timetree/calendar.py", line 55, in __init__
    self.data = EntitiesCalendarData(
  File "/config/custom_components/timetree/calendar.py", line 114, in __init__
    self._entities = timetree_object.get_upcoming_events(self._calendar.id, 'Europe/Berlin', 7).data
  File "/config/custom_components/timetree/timetree_sdk/api.py", line 83, in get_upcoming_events
    return EventResponse.new_from_json_dict(response.json())
  File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
    return cls(**d)
  File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in __init__
    self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
  File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in <listcomp>
    self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
  File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
    return cls.new_from_json_dict(data)
  File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
    return cls(**d)
  File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 164, in __init__
    self.attributes = self.get_or_new_from_json_dict(attributes, EventAttributes)
  File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
    return cls.new_from_json_dict(data)
  File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
    return cls(**d)
TypeError: __init__() got an unexpected keyword argument 'location_lat'

Any Ideas what I can do?

**Comment by thstorm** [comment]
PS:
When I manually try to execute the script I get the following error (Hope this helps)

bash-5.1# python calendar.py 
Traceback (most recent call last):
  File "/config/custom_components/timetree/calendar.py", line 7, in <module>
    from .timetree_sdk import TimeTreeApi
ImportError: attempted relative import with no known parent package
bash-5.1#

**Comment by acdcnow** [comment]
same issue:
2022-07-26 10:15:19 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up timetree platform for calendar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/timetree/calendar.py", line 38, in setup_platform
EntitiesCalendarDevice(
File "/config/custom_components/timetree/calendar.py", line 55, in __init__
self.data = EntitiesCalendarData(
File "/config/custom_components/timetree/calendar.py", line 114, in __init__
self._entities = timetree_object.get_upcoming_events(self._calendar.id, 'Europe/Berlin', 7).data
File "/config/custom_components/timetree/timetree_sdk/api.py", line 83, in get_upcoming_events
return EventResponse.new_from_json_dict(response.json())
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in __init__
self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 152, in <listcomp>
self.data = [self.get_or_new_from_json_dict(it, EventDataResponse) for it in data]
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
return cls.new_from_json_dict(data)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
File "/config/custom_components/timetree/timetree_sdk/models/responses.py", line 164, in __init__
self.attributes = self.get_or_new_from_json_dict(attributes, EventAttributes)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 18, in get_or_new_from_json_dict
return cls.new_from_json_dict(data)
File "/config/custom_components/timetree/timetree_sdk/models/base.py", line 11, in new_from_json_dict
return cls(**d)
TypeError: EventAttributes.__init__() got an unexpected keyword argument 'location_lat'

**Comment by frantathefranta** [comment]
You can find the solution here: https://github.com/Micha95/homeassistant_timetree_calendar/issues/1
