### ISSUE TITLE
After solution from issues #1 AttributeError: 'EventAttributes' object has no attribute 'start_at'

### ISSUE THREAD

**Issue by acdcnow** [Micha95/homeassistant_timetree_calendar#6]
Used the zip file and added them into now the error is.

AttributeError: 'EventAttributes' object has no attribute 'start_at'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/timetree/calendar.py", line 74, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/timetree/calendar.py", line 148, in update
    start = entity.attributes.start_at
AttributeError: 'EventAttributes' object has no attribute 'start_at'

**Comment by acdcnow** [comment]
no help so needs to be deleted this customer integration as it is not working any more!

**Comment by acdcnow** [comment]
dead integration
